name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-13-arm64

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: cargo install
    - name: Build
      run: cargo build --verbose --release
